Add terraform validate section to workflow

diff --git a/.github/workflows/action-terraform-verify.yml b/.github/workflows/action-terraform-verify.yml
--- a/.github/workflows/action-terraform-verify.yml
+++ b/.github/workflows/action-terraform-verify.yml
@@ -1,4 +1,4 @@
-name: Validate terraform fmt
+name: Validate Terraform fmt
 on:
   pull_request:
     branches:
@@ -10,9 +10,9 @@ permissions:
   contents: read
 
 jobs:
-  validate:
+  terraform_fmt:
     runs-on: ubuntu-latest
-    name: terraform fmt check
+    name: Terraform fmt check
     outputs:
       CHECK_STATUS: "${{ env.CHECK_STATUS }}"
     steps:
@@ -24,29 +24,65 @@ jobs:
         uses: jitterbit/get-changed-files@v1
         with:
           format: "space-delimited"
-      - name: Configure terraform
+      - name: Configure Terraform
         uses: hashicorp/setup-terraform@v2
         with:
           terraform_version: 1.2.4
       - name: Validate terraform fmt (added_modified)
         run: |
           set +e
-
           echo "CHECK_STATUS=0" >> $GITHUB_ENV
-
           for changed_file in ${{ steps.pr_files.outputs.added_modified }}; do
             echo "Checking terraform fmt on ${changed_file}..."
-
             if [[ $changed_file == *.tf ]]; then
               terraform fmt -check $changed_file
               FMT_STATUS=$(echo $?)
-
               if [[ $FMT_STATUS -ne 0 ]]; then
                 echo "❌ terraform fmt failed - ${changed_file}" >> $GITHUB_STEP_SUMMARY
                 echo "CHECK_STATUS=1" >> $GITHUB_ENV
               fi
             fi
           done
-      - name: Process check
+      - name: Process fmt check
+        if: always()
+        run: exit $CHECK_STATUS
+
+  terraform_validate:
+    runs-on: ubuntu-latest
+    name: Terraform validate check
+    needs: terraform_fmt
+    outputs:
+      CHECK_STATUS: "${{ env.CHECK_STATUS }}"
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 2
+      - name: Fetch changed files
+        id: pr_files
+        uses: jitterbit/get-changed-files@v1
+        with:
+          format: "space-delimited"
+      - name: Configure Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: 1.2.4
+      - name: Initialize Terraform
+        run: terraform init
+      - name: Validate Terraform syntax
+        run: |
+          set +e
+          echo "CHECK_STATUS=0" >> $GITHUB_ENV
+          for changed_file in ${{ steps.pr_files.outputs.added_modified }}; do
+            echo "Validating Terraform syntax in ${changed_file}..."
+            if [[ $changed_file == *.tf ]]; then
+              terraform validate
+              VALIDATE_STATUS=$?
+              if [[ $VALIDATE_STATUS -ne 0 ]]; then
+                echo "❌ terraform validate failed - ${changed_file}" >> $GITHUB_STEP_SUMMARY
+                echo "CHECK_STATUS=1" >> $GITHUB_ENV
+              fi
+            fi
+          done
+      - name: Process validate check
         if: always()
         run: exit $CHECK_STATUS
